base_url = "https://egemengol.com"
title = "Personal website of Egemen Göl"
author = "Egemen Göl"
description = "Personal website of Egemen Göl"

compile_sass = true
minify_html = true
hard_link_static = false

build_search_index = true

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

taxonomies = [
    { name = "tags", feed = false, paginate_by = 8, list_template = "tags/list.html", single_template = "tags/single.html" },
    { name = "series", feed = true, paginate_by = 8, list_template = "series/list.html", single_template = "series/single.html" },
]

exclude_paginated_pages_in_sitemap = "all"

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

[extra]

[search]
include_description = true
